### ISSUE TITLE
fatal error: licensemanager.h: No such file or directory

### ISSUE THREAD

**Issue by starsyi** [genometools/vstree#11]
I found the following error when compiling the software

```
 fatal error: licensemanager.h: No such file or directory
 #include "licensemanager.h"
          ^~~~~~~~~~~~~~~~~~
```

where can i find licensemanager.h file ???

**Comment by satta** [comment]
This is part of a non-free component that is no longer necessary after the open-source release.
Please build with the `licensemanager=no` parameter for `make` (probably run `make clean` before).
